<?php
declare(strict_types=1);
const TARGET_VERSION='0.8.0';
function out(string $m=''):void{echo $m.PHP_EOL;}
function fail(string $m,int $c=1):never{out('[ERRO] '.$m);exit($c);}
function tableExists(PDO $pdo,string $t):bool{$s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t');$s->execute(['t'=>$t]);return (int)$s->fetchColumn()>0;}
function updateConfigVersion(string $path,string $v):void{$c=file_get_contents($path);if($c===false)fail('Não foi possível ler config/config.php.');$pattern="/define\\s*\\(\\s*['\"]APP_VERSION['\"]\\s*,\\s*['\"]([^'\"]*)['\"]\\s*\\)\\s*;/";if(preg_match($pattern,$c,$m)&&($m[1]??'')===$v){out('[OK] APP_VERSION já está em '.$v.'.');return;}$bak=$path.'.bak-'.date('Ymd-His');if(!copy($path,$bak))fail('Não foi possível criar backup do config.');if(preg_match($pattern,$c)){$n=preg_replace($pattern,"define('APP_VERSION', '".$v."');",$c,1);$msg='[OK] APP_VERSION alterado para '.$v.'.';}else{$def="define('APP_VERSION', '".$v."');";if(preg_match('/declare\\s*\\(\\s*strict_types\\s*=\\s*1\\s*\\)\\s*;/',$c,$m,PREG_OFFSET_CAPTURE)){$o=$m[0][1]+strlen($m[0][0]);$n=substr($c,0,$o).PHP_EOL.PHP_EOL.$def.substr($c,$o);}elseif(preg_match('/<\\?php\\s*/',$c,$m,PREG_OFFSET_CAPTURE)){$o=$m[0][1]+strlen($m[0][0]);$n=substr($c,0,$o).PHP_EOL.PHP_EOL.$def.substr($c,$o);}else{$n="<?php".PHP_EOL.$def.PHP_EOL.$c;}$msg='[OK] APP_VERSION não existia e foi adicionada como '.$v.'.';}if($n===null||file_put_contents($path,$n,LOCK_EX)===false)fail('Não foi possível atualizar config/config.php. Backup: '.basename($bak));out($msg);out('[OK] Backup do config: '.basename($bak));}
function seedPermission(PDO $pdo):int{$s=$pdo->prepare("INSERT INTO permissoes (nome,slug,grupo,descricao,ordem) VALUES ('Gerenciar formulários','formularios.gerenciar','Conteúdo','Criar formulários públicos, consultar e exportar respostas.',47) ON DUPLICATE KEY UPDATE nome=VALUES(nome),grupo=VALUES(grupo),descricao=VALUES(descricao),ordem=VALUES(ordem)");$s->execute();$q=$pdo->query("SELECT id FROM permissoes WHERE slug='formularios.gerenciar' LIMIT 1");return (int)$q->fetchColumn();}
function addPerm(PDO $pdo,string $perfil,int $perm):void{$s=$pdo->prepare('SELECT id FROM perfis WHERE slug=:slug LIMIT 1');$s->execute(['slug'=>$perfil]);$pid=(int)$s->fetchColumn();if($pid>0)$pdo->prepare('INSERT IGNORE INTO perfil_permissoes (perfil_id,permissao_id) VALUES (:p,:m)')->execute(['p'=>$pid,'m'=>$perm]);}
function installRoute(string $root):void{$rulesPath=$root.'/rotas_v0.8.0.htaccess';if(!is_file($rulesPath))fail('rotas_v0.8.0.htaccess não encontrado.');$rules=trim((string)file_get_contents($rulesPath));$ht=$root.'/.htaccess';$begin='# BEGIN PORTAL_IECLB_ROTAS_V080';$end='# END PORTAL_IECLB_ROTAS_V080';$block=$begin.PHP_EOL.$rules.PHP_EOL.$end;$existing=is_file($ht)?(string)file_get_contents($ht):'';$pattern='/(?:\\R)?'.preg_quote($begin,'/').'.*?'.preg_quote($end,'/').'(?:\\R)?/s';$clean=trim((string)preg_replace($pattern,PHP_EOL,$existing));if(is_file($ht)){$bak=$ht.'.bak-v080-'.date('Ymd-His');if(!copy($ht,$bak))fail('Não foi possível criar backup do .htaccess.');out('[OK] Backup do .htaccess: '.basename($bak));}$new=$block.PHP_EOL.($clean!==''?PHP_EOL.$clean.PHP_EOL:'');if(file_put_contents($ht,$new,LOCK_EX)===false)fail('Não foi possível gravar .htaccess.');out('[OK] Rota /formulario/{slug} instalada/verificada.');}
$root=__DIR__;$config=$root.'/config/config.php';$db=$root.'/mod/db/Database.php';out('Portal IECLB Parobé - atualização para v'.TARGET_VERSION);out(str_repeat('-',64));if(!is_file($config))fail('config/config.php não encontrado. Execute na raiz do portal.');if(!is_file($db))fail('mod/db/Database.php não encontrado.');foreach(['admin/formularios/index.php','admin/formularios/form.php','admin/formularios/respostas.php','admin/formularios/resposta.php','admin/formularios/exportar.php','formulario.php','app/Helpers/functions.php'] as $f)if(!is_file($root.'/'.$f))fail('Arquivo da v0.8.0 não encontrado: '.$f);require_once $config;require_once $db;out('Versão identificada: '.(defined('APP_VERSION')?(string)APP_VERSION:'não definida'));
try{$pdo=Database::connection();out('[OK] Conexão com o banco realizada.');foreach(['usuarios','perfis','permissoes','perfil_permissoes','menus','menu_itens'] as $t)if(!tableExists($pdo,$t))fail('A tabela '.$t.' não existe. Atualize primeiro até a v0.7.0.');$migration=$root.'/migrations/2026_08_18_v0.8.0.sql';if(!is_file($migration))fail('Migração v0.8.0 não encontrada.');$sql=(string)file_get_contents($migration);$statements=preg_split('/;\s*(?:\R|$)/',$sql) ?: [];foreach($statements as $statement){$statement=trim($statement);if($statement==='')continue;$pdo->exec($statement);}foreach(['formularios','formulario_campos','formulario_respostas','formulario_resposta_valores'] as $t)if(!tableExists($pdo,$t))fail('A tabela '.$t.' não foi criada.');out('[OK] Tabelas de formulários criadas/verificadas.');$perm=seedPermission($pdo);foreach(['administrador','secretaria','comunicacao'] as $p)addPerm($pdo,$p,$perm);out('[OK] Permissão de Formulários cadastrada.');$contactId=(int)$pdo->query("SELECT id FROM formularios WHERE slug='contato' AND status='publicado' AND ativo=1 LIMIT 1")->fetchColumn();$menu=(int)$pdo->query("SELECT id FROM menus WHERE localizacao='principal' LIMIT 1")->fetchColumn();if($menu>0 && $contactId>0){$c=$pdo->prepare("SELECT COUNT(*) FROM menu_itens WHERE menu_id=:m AND tipo='link' AND url='formulario/contato'");$c->execute(['m'=>$menu]);if((int)$c->fetchColumn()===0){$i=$pdo->prepare("INSERT INTO menu_itens (menu_id,tipo,titulo,url,ordem,ativo) VALUES (:m,'link','Contato','formulario/contato',50,1)");$i->execute(['m'=>$menu]);out('[OK] Item Contato adicionado ao Menu Principal.');}else out('[OK] Item Contato já existe no Menu Principal.');}}
catch(Throwable $e){fail('Falha ao atualizar o banco: '.$e->getMessage());}
installRoute($root);updateConfigVersion($config,TARGET_VERSION);out(str_repeat('-',64));out('Atualização concluída com sucesso.');out('Novo módulo: Formulários e Respostas.');out('Formulário inicial: /formulario/contato');
