<?php
require_once __DIR__ . '/bootstrap.php';
$pdo=Database::connection();
$slug=routeSlug('formulario');
if($slug===''){http_response_code(404);exit('Formulário não encontrado.');}
$stmt=$pdo->prepare("SELECT * FROM formularios WHERE slug=:slug AND status='publicado' AND ativo=1 AND (publicado_em IS NULL OR publicado_em<=NOW()) LIMIT 1");$stmt->execute(['slug'=>$slug]);$form=$stmt->fetch();
if(!$form){http_response_code(404);exit('Formulário não encontrado.');}
redirectCanonicalContent('formulario', (string)$form['slug']);
$stmt=$pdo->prepare('SELECT * FROM formulario_campos WHERE formulario_id=:id AND ativo=1 ORDER BY ordem,id');$stmt->execute(['id'=>$form['id']]);$fields=$stmt->fetchAll();
$errors=[];$old=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
    $old=$_POST;
    if(!Csrf::validate($_POST['_token'] ?? null)) $errors[]='Sua sessão expirou. Atualize a página e tente novamente.';
    if(trim((string)($_POST['website'] ?? ''))!=='') $errors[]='Não foi possível enviar o formulário.';
    $last=(int)($_SESSION['_last_form_submit'] ?? 0); if($last>0 && time()-$last<3) $errors[]='Aguarde alguns segundos antes de enviar novamente.';
    $values=[];
    foreach($fields as $field){$key='campo_'.(int)$field['id'];$value=trim((string)($_POST[$key] ?? ''));if($field['tipo']==='checkbox')$value=isset($_POST[$key])?'Sim':'';if((int)$field['obrigatorio']===1 && $value==='')$errors[]='Preencha o campo "'.$field['rotulo'].'".';if($value!=='' && $field['tipo']==='email' && !filter_var($value,FILTER_VALIDATE_EMAIL))$errors[]='Informe um e-mail válido.';if($value!=='' && $field['tipo']==='numero' && !is_numeric(str_replace(',','.',$value)))$errors[]='Informe um número válido em "'.$field['rotulo'].'".';if($field['tipo']==='select' && $value!==''){$opts=array_values(array_filter(array_map('trim',preg_split('/\R/',(string)$field['opcoes'])?:[])));if(!in_array($value,$opts,true))$errors[]='Seleção inválida em "'.$field['rotulo'].'".';}$values[(int)$field['id']]=mb_substr($value,0,20000);}
    if(!$errors){try{$pdo->beginTransaction();$stmt=$pdo->prepare('INSERT INTO formulario_respostas (formulario_id,status,ip,user_agent,origem) VALUES (:formulario,\'nova\',:ip,:ua,:origem)');$stmt->execute(['formulario'=>$form['id'],'ip'=>isset($_SERVER['REMOTE_ADDR'])?mb_substr((string)$_SERVER['REMOTE_ADDR'],0,45):null,'ua'=>isset($_SERVER['HTTP_USER_AGENT'])?mb_substr((string)$_SERVER['HTTP_USER_AGENT'],0,500):null,'origem'=>isset($_SERVER['HTTP_REFERER'])?mb_substr((string)$_SERVER['HTTP_REFERER'],0,500):null]);$rid=(int)$pdo->lastInsertId();$ins=$pdo->prepare('INSERT INTO formulario_resposta_valores (resposta_id,campo_id,valor) VALUES (:resposta,:campo,:valor)');foreach($values as $cid=>$value)$ins->execute(['resposta'=>$rid,'campo'=>$cid,'valor'=>$value!==''?$value:null]);$pdo->commit();try{FormNotificationService::notifyResponse($pdo,$form,$fields,$values,$rid);}catch(Throwable $notificationError){}$_SESSION['_last_form_submit']=time();Session::flash('form_success',(string)($form['mensagem_sucesso'] ?: 'Sua resposta foi enviada com sucesso.'));header('Location: '.contentUrl('formulario',(string)$form['slug']));exit;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$errors[]='Não foi possível registrar sua resposta. Tente novamente.';}}
}
$metaTitle=(string)$form['titulo'].' - IECLB Parobé';$metaDescription=trim(strip_tags((string)$form['descricao'])) ?: 'Formulário da IECLB Parobé';$canonicalUrl=contentUrl('formulario',(string)$form['slug']);
require themeFile($pdo, 'header.php');
$success=Session::flash('form_success');
?>
<section class="py-5"><div class="container"><div class="row justify-content-center"><div class="col-lg-8 col-xl-7"><div class="mb-4"><h1 class="display-6 fw-bold mb-3"><?= e($form['titulo']) ?></h1><?php if($form['descricao']): ?><p class="lead text-secondary"><?= nl2br(e((string)$form['descricao'])) ?></p><?php endif; ?></div><?php if($success): ?><div class="alert alert-success p-4"><?= e($success) ?></div><?php else: ?><?php if($errors): ?><div class="alert alert-danger"><strong>Confira os campos:</strong><ul class="mb-0 mt-2"><?php foreach(array_unique($errors) as $err): ?><li><?= e($err) ?></li><?php endforeach; ?></ul></div><?php endif; ?><form method="post" class="public-form card border-0 shadow-sm"><div class="card-body p-4 p-md-5"><?= Csrf::field() ?><div class="visually-hidden" aria-hidden="true"><label>Website<input tabindex="-1" autocomplete="off" name="website"></label></div><?php foreach($fields as $field): $key='campo_'.(int)$field['id'];$value=(string)($old[$key] ?? ''); ?><div class="mb-4"><?php if($field['tipo']==='checkbox'): ?><div class="form-check"><input class="form-check-input" type="checkbox" id="<?= e($key) ?>" name="<?= e($key) ?>" value="1" <?= isset($old[$key])?'checked':'' ?> <?= (int)$field['obrigatorio']===1?'required':'' ?>><label class="form-check-label" for="<?= e($key) ?>"><?= e($field['rotulo']) ?><?= (int)$field['obrigatorio']===1?' *':'' ?></label></div><?php else: ?><label class="form-label fw-semibold" for="<?= e($key) ?>"><?= e($field['rotulo']) ?><?= (int)$field['obrigatorio']===1?' *':'' ?></label><?php if($field['tipo']==='textarea'): ?><textarea class="form-control" rows="6" id="<?= e($key) ?>" name="<?= e($key) ?>" placeholder="<?= e((string)$field['placeholder']) ?>" <?= (int)$field['obrigatorio']===1?'required':'' ?>><?= e($value) ?></textarea><?php elseif($field['tipo']==='select'): ?><select class="form-select" id="<?= e($key) ?>" name="<?= e($key) ?>" <?= (int)$field['obrigatorio']===1?'required':'' ?>><option value="">Selecione...</option><?php foreach(array_values(array_filter(array_map('trim',preg_split('/\R/',(string)$field['opcoes'])?:[]))) as $opt): ?><option value="<?= e($opt) ?>" <?= $value===$opt?'selected':'' ?>><?= e($opt) ?></option><?php endforeach; ?></select><?php else: $inputType=['email'=>'email','telefone'=>'tel','numero'=>'number','data'=>'date'][$field['tipo']] ?? 'text'; ?><input class="form-control" type="<?= e($inputType) ?>" id="<?= e($key) ?>" name="<?= e($key) ?>" value="<?= e($value) ?>" placeholder="<?= e((string)$field['placeholder']) ?>" <?= (int)$field['obrigatorio']===1?'required':'' ?>><?php endif; ?><?php endif; ?></div><?php endforeach; ?><button class="btn btn-primary btn-lg px-4">Enviar</button></div></form><?php endif; ?></div></div></div></section>
<?php require themeFile($pdo, 'footer.php'); ?>
