<?php
require_once __DIR__ . '/../../bootstrap.php';
Auth::requirePermission('newsletter.gerenciar');
$pdo=Database::connection();$error='';$defaults=['newsletter_enabled'=>'1','newsletter_double_optin'=>'1','newsletter_from_name'=>siteConfig($pdo,'site_nome',APP_NAME),'newsletter_from_email'=>siteConfig($pdo,'site_email',''),'newsletter_title'=>'Receba nossas novidades','newsletter_description'=>'Cadastre seu e-mail para receber notícias, agenda e informações da IECLB Parobé.'];$s=array_merge($defaults,siteConfigAll($pdo));
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Csrf::validate($_POST['_token']??null))$error='Token de segurança inválido.';else{try{$s['newsletter_enabled']=isset($_POST['newsletter_enabled'])?'1':'0';$s['newsletter_double_optin']=isset($_POST['newsletter_double_optin'])?'1':'0';$s['newsletter_from_name']=trim((string)($_POST['newsletter_from_name']??''));$s['newsletter_from_email']=strtolower(trim((string)($_POST['newsletter_from_email']??'')));$s['newsletter_title']=trim((string)($_POST['newsletter_title']??''));$s['newsletter_description']=trim((string)($_POST['newsletter_description']??''));if($s['newsletter_from_email']!==''&&!filter_var($s['newsletter_from_email'],FILTER_VALIDATE_EMAIL))throw new RuntimeException('Informe um e-mail remetente válido.');foreach($defaults as $k=>$_)saveSiteConfig($pdo,$k,$s[$k],in_array($k,['newsletter_enabled','newsletter_double_optin'],true)?'booleano':'texto');logAction($pdo,'newsletter.configuracoes','configuracoes');Session::flash('success','Configurações da newsletter atualizadas.');header('Location: '.url('admin/newsletter/configuracoes.php'));exit;}catch(Throwable $e){$error=$e->getMessage();}}
}
$pageTitle='Newsletter - Configurações';require __DIR__.'/../_header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Configurações da Newsletter</h1><p class="text-secondary mb-0">Controle inscrições, remetente e textos da página pública.</p></div><?php if(Auth::can('email.gerenciar')):?><a class="btn btn-outline-secondary" href="<?=e(url('admin/configuracoes/email.php'))?>"><i class="bi bi-envelope-gear me-1"></i> Configurar e-mail</a><?php endif;?></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php $mailIssue=MailService::configurationIssue($pdo, trim((string)$s['newsletter_from_email'])!==''?['from_email'=>(string)$s['newsletter_from_email']]:[]); if($mailIssue!==null):?><div class="alert alert-warning"><strong>Envio de e-mail:</strong> <?=e($mailIssue)?></div><?php endif;?>
<form method="post" class="card border-0 shadow-sm"><div class="card-body p-4"><?=Csrf::field()?><div class="row g-4"><div class="col-12"><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" name="newsletter_enabled" id="enabled" <?=$s['newsletter_enabled']==='1'?'checked':''?>><label class="form-check-label fw-semibold" for="enabled">Permitir novas inscrições</label></div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="newsletter_double_optin" id="optin" <?=$s['newsletter_double_optin']==='1'?'checked':''?>><label class="form-check-label fw-semibold" for="optin">Exigir confirmação por e-mail (double opt-in)</label><div class="form-text">Recomendado. O Portal enviará a confirmação usando o método definido em Configurações > E-mail.</div></div></div><div class="col-md-6"><label class="form-label">Nome do remetente da Newsletter</label><input class="form-control" name="newsletter_from_name" value="<?=e($s['newsletter_from_name'])?>"></div><div class="col-md-6"><label class="form-label">E-mail do remetente da Newsletter</label><input class="form-control" type="email" name="newsletter_from_email" value="<?=e($s['newsletter_from_email'])?>" placeholder="vazio = usar Configurações > E-mail"><div class="form-text">Se ficar vazio, será usado o remetente global do Portal.</div></div><div class="col-md-6"><label class="form-label">Título da página pública</label><input class="form-control" name="newsletter_title" value="<?=e($s['newsletter_title'])?>"></div><div class="col-md-6"><label class="form-label">Descrição</label><input class="form-control" name="newsletter_description" value="<?=e($s['newsletter_description'])?>"></div><div class="col-12"><button class="btn btn-primary">Salvar configurações</button> <a class="btn btn-outline-secondary" target="_blank" href="<?=e(url('newsletter'))?>">Ver página pública</a></div></div></div></form>
<?php require __DIR__.'/../_footer.php'; ?>
