CREATE TABLE IF NOT EXISTS eventos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    autor_id INT UNSIGNED NOT NULL,
    comunidade_id INT UNSIGNED NULL,
    tipo ENUM('culto','evento') NOT NULL DEFAULT 'evento',
    titulo VARCHAR(220) NOT NULL,
    slug VARCHAR(240) NOT NULL UNIQUE,
    resumo TEXT NULL,
    descricao LONGTEXT NULL,
    local VARCHAR(255) NULL,
    endereco VARCHAR(255) NULL,
    data_inicio DATETIME NOT NULL,
    data_fim DATETIME NULL,
    santa_ceia TINYINT(1) NOT NULL DEFAULT 0,
    imagem_capa_id BIGINT UNSIGNED NULL,
    status ENUM('rascunho','publicado','cancelado','arquivado') NOT NULL DEFAULT 'rascunho',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_eventos_autor FOREIGN KEY (autor_id) REFERENCES usuarios(id),
    CONSTRAINT fk_eventos_comunidade FOREIGN KEY (comunidade_id) REFERENCES comunidades(id) ON DELETE SET NULL,
    CONSTRAINT fk_eventos_imagem_capa FOREIGN KEY (imagem_capa_id) REFERENCES midias(id) ON DELETE SET NULL,
    INDEX idx_eventos_status_data (status, data_inicio),
    INDEX idx_eventos_tipo_data (tipo, data_inicio),
    INDEX idx_eventos_comunidade (comunidade_id),
    INDEX idx_eventos_imagem_capa (imagem_capa_id)
) ENGINE=InnoDB;
