<?php
require_once __DIR__.'/../../bootstrap.php'; Auth::requirePermission('configuracoes.gerenciar'); $pdo=Database::connection();$error='';
$serverMb=max(1,(int)floor((defined('UPLOAD_MAX_SIZE')?(int)UPLOAD_MAX_SIZE:10485760)/1048576));$defaults=['media_upload_max_mb'=>(string)$serverMb,'media_organize_year_month'=>'1','media_allow_documents'=>'1','media_delete_file_on_delete'=>'1'];$s=array_merge($defaults,siteConfigAll($pdo));
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Csrf::validate($_POST['_token']??null))$error='Token de segurança inválido.'; else try{$s['media_upload_max_mb']=(string)max(1,min($serverMb,(int)($_POST['media_upload_max_mb']??$serverMb)));foreach(['media_organize_year_month','media_allow_documents','media_delete_file_on_delete'] as $k)$s[$k]=isset($_POST[$k])?'1':'0';foreach($defaults as $k=>$_)saveSiteConfig($pdo,$k,$s[$k],$k==='media_upload_max_mb'?'numero':'booleano');logAction($pdo,'configuracoes.midia','configuracoes');Session::flash('success','Configurações de mídia atualizadas.');header('Location: '.url('admin/configuracoes/midia.php'));exit;}catch(Throwable $e){$error=$e->getMessage();}
}
$pageTitle='Configurações de mídia';require __DIR__.'/../_header.php';?>
<h1 class="h3 mb-1">Mídia</h1><p class="text-secondary mb-4">Regras de upload e armazenamento da Biblioteca de Mídia.</p><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post" class="card border-0 shadow-sm"><div class="card-body p-4"><?=Csrf::field()?><div class="row g-3">
<div class="col-md-6"><label class="form-label">Tamanho máximo por arquivo</label><div class="input-group"><input class="form-control" type="number" min="1" max="<?=$serverMb?>" name="media_upload_max_mb" value="<?=e($s['media_upload_max_mb'])?>"><span class="input-group-text">MB</span></div><div class="form-text">Limite máximo definido no servidor/config.php: <?=$serverMb?> MB.</div></div>
<div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="media_organize_year_month" id="org" <?=$s['media_organize_year_month']==='1'?'checked':''?>><label class="form-check-label" for="org">Organizar uploads em pastas por ano/mês</label></div></div>
<div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="media_allow_documents" id="docs" <?=$s['media_allow_documents']==='1'?'checked':''?>><label class="form-check-label" for="docs">Permitir PDF, Word, Excel, PowerPoint e TXT</label></div></div>
<div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="media_delete_file_on_delete" id="del" <?=$s['media_delete_file_on_delete']==='1'?'checked':''?>><label class="form-check-label" for="del">Apagar o arquivo físico quando a mídia for excluída da biblioteca</label></div></div>
<div class="col-12"><button class="btn btn-primary">Salvar mídia</button></div></div></div></form><?php require __DIR__.'/../_footer.php';?>
