<?php
require_once __DIR__.'/../../bootstrap.php'; Auth::requirePermission('configuracoes.gerenciar');$pdo=Database::connection();$error='';
$defaults=['privacy_page_id'=>'','privacy_footer_link'=>'1','privacy_allow_search_engines'=>'1'];$s=array_merge($defaults,siteConfigAll($pdo));
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Csrf::validate($_POST['_token']??null))$error='Token de segurança inválido.';else try{$s['privacy_page_id']=trim((string)($_POST['privacy_page_id']??''));$s['privacy_footer_link']=isset($_POST['privacy_footer_link'])?'1':'0';$s['privacy_allow_search_engines']=isset($_POST['privacy_allow_search_engines'])?'1':'0';if($s['privacy_page_id']!==''){$st=$pdo->prepare("SELECT 1 FROM paginas WHERE id=:id AND status='publicado'");$st->execute(['id'=>(int)$s['privacy_page_id']]);if(!$st->fetchColumn())throw new RuntimeException('Selecione uma página publicada válida.');}foreach($defaults as $k=>$_)saveSiteConfig($pdo,$k,$s[$k],str_ends_with($k,'_id')?'numero':'booleano');logAction($pdo,'configuracoes.privacidade','configuracoes');Session::flash('success','Configurações de privacidade atualizadas.');header('Location: '.url('admin/configuracoes/privacidade.php'));exit;}catch(Throwable $e){$error=$e->getMessage();}
}
$pages=$pdo->query("SELECT id,titulo,slug FROM paginas WHERE status='publicado' AND (publicado_em IS NULL OR publicado_em<=NOW()) ORDER BY titulo")->fetchAll();$pageTitle='Privacidade';require __DIR__.'/../_header.php';?>
<h1 class="h3 mb-1">Privacidade</h1><p class="text-secondary mb-4">Política de privacidade e visibilidade para mecanismos de busca.</p><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post" class="card border-0 shadow-sm"><div class="card-body p-4"><?=Csrf::field()?>
<div class="mb-4"><label class="form-label">Página da Política de Privacidade</label><select class="form-select" name="privacy_page_id"><option value="">Nenhuma página definida</option><?php foreach($pages as $p):?><option value="<?=(int)$p['id']?>" <?=(string)$s['privacy_page_id']===(string)$p['id']?'selected':''?>><?=e($p['titulo'])?></option><?php endforeach;?></select><div class="form-text">Crie a política em Páginas e publique-a antes de selecioná-la aqui.</div></div>
<div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" id="pfl" name="privacy_footer_link" <?=$s['privacy_footer_link']==='1'?'checked':''?>><label class="form-check-label" for="pfl">Exibir link para a Política de Privacidade no rodapé</label></div>
<div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" id="idx" name="privacy_allow_search_engines" <?=$s['privacy_allow_search_engines']==='1'?'checked':''?>><label class="form-check-label" for="idx">Permitir que mecanismos de busca indexem o portal</label></div>
<div class="alert alert-light border">Desmarcar a indexação aplica <code>noindex</code> global e bloqueia o rastreamento no <code>robots.txt</code>. A opção de SEO Geral continua sendo respeitada em conjunto.</div><button class="btn btn-primary">Salvar privacidade</button></div></form><?php require __DIR__.'/../_footer.php';?>
